{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-backup-secret
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.backup.credentials.key }}
  ACCESS_SECRET_KEY: {{ .Values.backup.credentials.secretkey }}
{{ end }}