apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  labels:
    cnpg.io/cluster: mycluster
spec:
  {{ if eq .Values.clustermode.enabled true}}
  instances: {{ .Values.replicaCount }}
  {{ else }}
  instances: 1
  {{ end }}
  storage:
    pvcTemplate:
      accessModes:
        - {{ .Values.storage.accessmode }}
      resources:
        requests:
          storage: {{ .Values.storage.size }}
      storageClassName: {{ .Values.storage.storageclass }}
      volumeMode: {{ .Values.storage.VolumeMode }}
    resizeInUseVolumes: {{ .Values.storage.resize }}
  {{ if eq .Values.storage.WalStorage.enabled true}}
  WalStorage:
    size: {{ .Values.storage.WalStorage.size }}
  {{ end }}
  imageName: {{ .Values.image.repository }}:{{ .Values.image.tag }}
  resources:
    requests:
      cpu: {{ .Values.resources.requests.cpu }}
      memory: {{ .Values.resources.requests.memory }}
    limits:
      cpu: {{ .Values.resources.limits.cpu }}
      memory: {{ .Values.resources.limits.memory }}
  {{- if .Values.affinity.enabled }}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: {{ .Values.affinity.nodeAffinity.key }}
            operator: In
            values:
            - {{ .Values.affinity.nodeAffinity.value}}
  {{- if .Values.affinity.podanitaffinity.enabled }}
    podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: cnpg.io/cluster
              operator: In
              values:
                - "{{ .Release.Name }}"
        topologyKey: kubernetes.io/hostname
  {{ end }}                  
  {{ end }}  
  postgresql:
  parameters:
{{ toYaml .Values.postgresql.parameters | indent 4 }}   
  enableSuperuserAccess: {{ .Values.superuser.enabled }}
  superuserSecret:
    name: {{ .Values.superuser.secretName }}
  {{- if .Values.backup.enabled }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.backup.destinationPath }}
      endpointURL: {{ .Values.backup.endpointURL }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.backup.credentials.secretName }}
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: {{ .Values.backup.credentials.secretName }}
          key: ACCESS_SECRET_KEY
      wal:
        compression: {{ .Values.backup.wal.compression }}
        maxParallel: {{ .Values.backup.wal.maxParallel }}
      data:
        compression: {{ .Values.backup.data.compression }}
{{- end }}