{{ if eq .Values.superuser.enabled true}}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser-secret
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ .Values.superuser.password }}
{{ end }}