{{- if .Values.backup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Release.Name }}-backup
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  backupOwnerReference: cluster
  cluster:
    name: {{ .Release.Name }}
  target: "primary"  
{{- end }}