apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-bootstrap
  namespace: argocd
spec:
  generators:
    - list:
        elements:
{{- range .Values.applications }}
          - name: {{ .name }}
            namespace: {{ .namespace }}
            repoURL: {{ .repoURL }}
            version: {{ .version }}
{{- if .chart }}
            chart: {{ .chart }}
{{- end }}
{{- if .path }}
            path: {{ .path }}
{{- end }}
{{- end }}

  template:
    metadata:
      name: '{{`{{name}}`}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{namespace}}`}}'

      source:
        repoURL: '{{`{{repoURL}}`}}'
        targetRevision: '{{`{{version}}`}}'
        chart: '{{`{{chart}}`}}'
        path: '{{`{{path}}`}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - Replace=true
